name: Build

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: build-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc

            - name: Enable Corepack
              run: corepack enable

            - name: Install dependencies
              run: yarn install --immutable

            - name: Lint
              run: yarn lint

            - name: Compile
              run: yarn compile
